# Generated by Django 5.0 on 2025-10-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0007_review_is_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
                ('center_lat', models.FloatField(help_text='Latitude for map centering')),
                ('center_lng', models.FloatField(help_text='Longitude for map centering')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoviePopularity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.state')),
            ],
            options={
                'ordering': ['-purchase_count', '-view_count'],
                'unique_together': {('movie', 'state')},
            },
        ),
    ]
