# Generated by Django 5.0 on 2025-09-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='PG', max_length=10),
        ),
    ]
